### ISSUE TITLE
Things missing in the theme without styling supports in the theming API

### ISSUE THREAD

**Issue by teabyii** [teabyii/vscode-ayu#9]
- [x] Add left border to sidebar - https://github.com/Microsoft/vscode/issues/26530
- [x] Themeing for editor squiggles - https://github.com/Microsoft/vscode/issues/16204 + https://github.com/Microsoft/vscode/issues/9819
- [ ] Feature request: bold_folder_labels setting like Sublime's -
 https://github.com/Microsoft/vscode/issues/10748
- [ ] Hide sidebar's Tree View/Explorer arrows - https://github.com/Microsoft/vscode/issues/25655

**Comment by teabyii** [comment]
@pahen 

Thank you for your PR ! :tada::tada::tada:

We track the things which maybe can be fixed with theme API supports in the future here.

**Comment by pahen** [comment]
Perfect! 🕺

**Comment by ajitid** [comment]
Add these too:
[ ] Text selection color (find, search, etc) https://github.com/Microsoft/vscode/issues/25966
[ ] Allow theming of parameter hints https://github.com/Microsoft/vscode/issues/26671

**Comment by pahen** [comment]
The "Text selection color" should work already. Can you provide a screenshot where it doesn't work @ajitid? And what version of VSCode are you running?

**Comment by ajitid** [comment]
Latest in stable release, 1.12.2.
Is it available in insiders build and not in stable?

**Comment by pahen** [comment]
Correct. It was added after 1.12.2 was released. Should work in insiders build.

**Comment by pahen** [comment]
The same is valid for "Allow theming of parameter hints". Should work in insiders build.

**Comment by ajitid** [comment]
Okay, removed. Thanks!

**Comment by pahen** [comment]
I moved out the relevant stuff into own issues so I think we can close this now @teabyii
